repos: #run pre-commit install you dingus
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: python -m unittest discover
        language: python
        'types': [python]
        args: ["-p '*test.py'"] # Probably this option is absolutely not needed.
        pass_filenames: false
        stages: [commit]
